################################################################################
# FILE         : modules/rds/main.tf
# DESCRIPTION  : RDS MySQL instance with auto-generated password stored
#                in Secrets Manager, custom parameter group, and full
#                encryption at rest and in transit.
#
# RESOURCES CREATED:
#   1. random_password              — Cryptographically secure DB password
#   2. aws_secretsmanager_secret    — Secrets Manager secret container
#   3. aws_secretsmanager_secret_version — Stores the actual password value
#   4. aws_db_parameter_group       — Custom MySQL 8.0 parameters
#   5. aws_db_instance              — RDS MySQL Free Tier instance
#
# SECURITY CONTROLS:
#   - Password generated internally — never in variables or tfvars
#   - Password stored in Secrets Manager — app retrieves at runtime
#   - Storage encrypted with AWS managed key (AES-256)
#   - In-transit encryption enforced via parameter group
#   - Deployed in isolated database subnets — no internet route
#   - Security Group allows port 3306 from App SG only
#
# AUTHOR       : DevOps Platform Engineering Team
# REPOSITORY   : aws-enterprise-3tier-infrastructure-iac
# MANAGED BY   : Terraform
################################################################################

################################################################################
# RESOURCE 1: RANDOM PASSWORD GENERATION
#
# Generates a 32-character cryptographically secure random password.
# The password is generated INSIDE Terraform — never supplied externally.
# special = true includes symbols for password complexity requirements.
# override_special limits symbols to those safe in connection strings —
# avoids characters like @ / " that break JDBC/ODBC connection URL parsing.
################################################################################

resource "random_password" "db_password" {
  length           = 32
  special          = true
  override_special = "!#$%^&*()-_=+[]{}|;:,.<>?"

  # lifecycle prevents password regeneration on subsequent terraform applies.
  # Without this, every apply would generate a new password, update
  # Secrets Manager, and trigger an RDS password rotation — causing
  # all application connections to fail until they retrieve the new password.
  lifecycle {
    ignore_changes = [result]
  }
}

################################################################################
# RESOURCE 2: SECRETS MANAGER SECRET CONTAINER
# Creates the named secret container in Secrets Manager.
# The actual password value is stored in Resource 3 (secret version).
# Separating container from value allows secret rotation without
# changing the secret ARN — application references never break.
################################################################################

resource "aws_secretsmanager_secret" "db_password" {
  name        = "${var.project_name}/${var.environment}/rds/master-password"
  description = "RDS master password for ${var.name_prefix} database instance. Auto-generated by Terraform. Retrieved at runtime by application via IAM role — never hardcoded."

  # Recovery window: when a secret is deleted, it enters a recovery window
  # before permanent deletion. 7 days allows accidental deletion recovery.
  # Set to 0 for immediate deletion in dev environments (faster teardown).
  recovery_window_in_days = 7

  tags = merge(var.common_tags, {
    Name = "${var.project_name}/${var.environment}/rds/master-password"
    Role = "DatabaseCredential"
  })
}

################################################################################
# RESOURCE 3: SECRETS MANAGER SECRET VERSION
# Stores the actual password as a JSON-encoded string.
# JSON format is the Secrets Manager convention — allows storing multiple
# fields in one secret (username, password, host, port, dbname).
# Applications use the JSON SDK to retrieve all connection details at once.
################################################################################

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id = aws_secretsmanager_secret.db_password.id

  # Store as JSON with all connection details — application retrieves
  # this entire object and parses it for the connection string
  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_password.result
    dbname   = var.db_name
    engine   = var.db_engine
    # Host and port added after RDS creation via separate process
    # or the application can retrieve from Secrets Manager + RDS endpoint output
  })
}

################################################################################
# RESOURCE 4: RDS PARAMETER GROUP
# A Parameter Group is a named collection of database engine parameters.
# We create a custom one (not use the default) because:
#   1. The default parameter group cannot be modified
#   2. Custom groups allow us to enforce security parameters
#   3. Custom groups allow performance tuning per environment
#   4. Tagging and naming consistency
#
# KEY PARAMETERS:
#   require_secure_transport = ON  → All connections must use TLS/SSL
#   slow_query_log = 1             → Log queries taking > long_query_time
#   long_query_time = 2            → Flag queries taking > 2 seconds
#   max_connections = 100          → Appropriate for db.t3.micro (1GB RAM)
################################################################################

resource "aws_db_parameter_group" "main" {
  name        = "${var.name_prefix}-mysql80-params"
  family      = "mysql8.0"
  description = "Custom MySQL 8.0 parameter group for ${var.name_prefix}. Enforces TLS, enables slow query logging, and tunes connection limits for db.t3.micro."

  # SECURITY: Force all connections to use SSL/TLS encryption in transit.
  # Without this, database credentials and query results travel in plaintext
  # on the network — a critical vulnerability in shared environments.
  parameter {
    name         = "require_secure_transport"
    value        = "ON"
    apply_method = "immediate"
  }

  # OBSERVABILITY: Enable slow query log for performance troubleshooting.
  # Queries exceeding long_query_time are logged to the MySQL error log
  # which is exported to CloudWatch Logs for analysis.
  parameter {
    name         = "slow_query_log"
    value        = "1"
    apply_method = "immediate"
  }

  # OBSERVABILITY: Flag queries taking longer than 2 seconds as slow.
  # Adjust this threshold based on your application's SLA requirements.
  parameter {
    name         = "long_query_time"
    value        = "2"
    apply_method = "immediate"
  }

  # PERFORMANCE: Maximum concurrent connections.
  # db.t3.micro has 1GB RAM — formula: (RAM in MB) / 12.5 = ~80 connections.
  # Setting 100 gives slight headroom while preventing memory exhaustion.
  parameter {
    name         = "max_connections"
    value        = "100"
    apply_method = "immediate"
  }

  # SECURITY: Disable LOCAL INFILE — prevents reading arbitrary local files
  # from the MySQL client, a known attack vector for data exfiltration.
  parameter {
    name         = "local_infile"
    value        = "0"
    apply_method = "immediate"
  }

  tags = merge(var.common_tags, {
    Name = "${var.name_prefix}-mysql80-params"
  })

  lifecycle {
    create_before_destroy = true
  }
}

################################################################################
# RESOURCE 5: RDS DB INSTANCE
#
# The actual database server. Placed in isolated database subnets.
# All security controls applied — encryption, parameter group, SG chain.
# Password sourced from the random_password resource above — never hardcoded.
################################################################################

resource "aws_db_instance" "main" {

  ##############################################################################
  # INSTANCE IDENTITY
  ##############################################################################
  identifier = "${var.name_prefix}-mysql"
  db_name    = var.db_name

  ##############################################################################
  # ENGINE CONFIGURATION
  ##############################################################################
  engine               = var.db_engine
  engine_version       = var.db_engine_version
  instance_class       = var.db_instance_class
  parameter_group_name = aws_db_parameter_group.main.name

  ##############################################################################
  # STORAGE CONFIGURATION
  # gp2 is used here — it is the Free Tier eligible storage type.
  # gp3 is not Free Tier eligible for RDS (unlike EC2 EBS where gp3 is free).
  # storage_encrypted = true — AES-256 encryption at rest — mandatory.
  ##############################################################################
  allocated_storage     = var.db_allocated_storage
  storage_type          = "gp2"
  storage_encrypted     = true

  ##############################################################################
  # CREDENTIALS
  # Username from variable. Password from random_password resource.
  # The password is marked sensitive in the random_password resource output.
  # It will appear as (sensitive) in terraform plan output.
  ##############################################################################
  username = var.db_username
  password = random_password.db_password.result

  ##############################################################################
  # NETWORK CONFIGURATION
  # Placed in the DB subnet group (database subnets — fully isolated).
  # Associated with the DB security group (port 3306 from App SG only).
  # publicly_accessible = false — no public IP, no internet route.
  ##############################################################################
  db_subnet_group_name   = var.db_subnet_group_name
  vpc_security_group_ids = [var.db_security_group_id]
  publicly_accessible    = false
  multi_az               = var.db_multi_az
  availability_zone      = null
  # null lets AWS choose the AZ — for single-AZ deployments

  ##############################################################################
  # BACKUP CONFIGURATION
  ##############################################################################
  backup_retention_period = var.db_backup_retention_period
  backup_window           = var.db_backup_window
  maintenance_window      = var.db_maintenance_window

  # Copy automated backups to all regions — disabled for Free Tier cost control
  copy_tags_to_snapshot = true
  skip_final_snapshot   = var.db_skip_final_snapshot

  final_snapshot_identifier = var.db_skip_final_snapshot ? null : "${var.name_prefix}-final-snapshot-${formatdate("YYYY-MM-DD-hhmm", timestamp())}"

  ##############################################################################
  # PROTECTION
  ##############################################################################
  deletion_protection = var.db_deletion_protection

  ##############################################################################
  # AUTO MINOR VERSION UPGRADE
  # Automatically applies minor engine version patches during the maintenance
  # window. Keeps the database patched without manual intervention.
  # Major version upgrades always require explicit opt-in.
  ##############################################################################
  auto_minor_version_upgrade = true

  ##############################################################################
  # PERFORMANCE INSIGHTS
  # Query-level monitoring — shows which SQL queries are consuming most
  # database resources. Free for 7-day retention window.
  # Invaluable for identifying N+1 queries and slow query patterns.
  ##############################################################################
  performance_insights_enabled          = var.db_performance_insights_enabled
  performance_insights_retention_period = var.db_performance_insights_enabled ? 7 : null

  ##############################################################################
  # ENHANCED MONITORING
  # OS-level metrics (CPU steal, memory, disk I/O) at 1-60 second granularity.
  # Interval 0 disables enhanced monitoring for Free Tier cost control.
  ##############################################################################
  monitoring_interval = var.db_monitoring_interval

  ##############################################################################
  # CLOUDWATCH LOG EXPORTS
  # Exports MySQL logs to CloudWatch Logs for centralised analysis.
  # error    : Database errors and warnings
  # slowquery: Queries exceeding long_query_time threshold
  # general  : All queries — very verbose, use only for debugging
  ##############################################################################
  enabled_cloudwatch_logs_exports = ["error", "slowquery"]

  tags = merge(var.common_tags, {
    Name = "${var.name_prefix}-mysql"
    Role = "PrimaryDatabase"
    Tier = "Database"
  })

  # Ensure parameter group and Secrets Manager secret exist before RDS
  depends_on = [
    aws_db_parameter_group.main,
    aws_secretsmanager_secret_version.db_password
  ]
}
